@host = localhost:1234
@userid= 61b064ae6822a02a735fe011
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjFiMDY0YWU2ODIyYTAyYTczNWZlMDExIn0sImlhdCI6MTYzOTA0ODE2NywiZXhwIjoxNjM5MDg0MTY3fQ.fRN2gmlb5u3FFmyqrT92D7BNGTHR_0sICbakaopTPao
@categoryId=61a1beaee4f4363c63ed4591
@itemId=61ab02da9297bc948a92a37e
@sellerId=61b064ae6822a02a735fe011
@reviewId=61ada666166f39cb74522c95
### User SignUp 

POST  /signup HTTP/1.1
Host:{{host}}
Content-Type: application/json

{
    "userName": "cas Seller",
    "firstName": "peter",
    "lastName": "parker",
    "password": "S@ngharsh123",
    "confirmPassword": "S@ngharsh123",
    "email": "teas12454@mail.com",
    "aadharNumber": 123456799012,
    "address": "hell",
    "isSeller": true
}

### login API
POST  /login HTTP/1.1
Host:{{host}}
Content-Type: application/json

{
    "userName":"vkd9977",
    "password":"Vish@l123"
}

### GET User Profiles
GET  /getProfile HTTP/1.1
Host:{{host}}
Content-Type: application/json
userId:{{userid}}

### Delete User Profiles
DELETE  /deleteUser HTTP/1.1
Host:{{host}}
Content-Type: application/json
userId:{{userid}}
token:{{token}}

### add Category
POST  /addCategory HTTP/1.1
Host:{{host}}
Content-Type: application/json
userId:{{userid}}
token:{{token}}

{
    "categoryName":"Books"
}
### add ItemDetails
POST  /addItemDetails HTTP/1.1
Host:{{host}}
Content-Type: application/json
userId:{{userid}}
categoryId:{{categoryId}}
token:{{token}}

{
    "itemName": "fansss",
    "price": 1000,
    "weight": 1000,
    "brand": "Tin fans"
}
### update ItemDetails
POST  /updateItemDetails HTTP/1.1
Host:{{host}}
Content-Type: application/json
userId:{{userid}}
categoryId:{{categoryId}}
token:{{token}}
itemId:{{itemId}}

{
    "brand": "Tin Electrical"
}
### GET getItems
GET  /getItems?sellerId=61b064ae6822a02a735fe011 HTTP/1.1
Host:{{host}}
Content-Type: application/json


### GET Categories
GET  /getCategories HTTP/1.1
Host:{{host}}
Content-Type: application/json

### DELETE ItemDetails
POST  /deleteItems HTTP/1.1
Host:{{host}}
Content-Type: application/json
userId:{{userid}}
token:{{token}}

{
 "items":["61b1f20deeebd65d88cd5de1","61b065266822a02a735fe017"]
}

### POST addToCart

POST  /addToCart HTTP/1.1
Host:{{host}}
Content-Type: application/json
userId:{{userid}}
itemId:{{itemId}}
token:{{token}}




### DELETE deleteFromCart

DELETE  /deleteFromCart HTTP/1.1
Host:{{host}}
Content-Type: application/json
userId:{{userid}}
itemId:{{itemId}}
token:{{token}}


### update deleteFromCart

PUT  /updateCartItem HTTP/1.1
Host:{{host}}
Content-Type: application/json
userId:{{userid}}
itemId:{{itemId}}
token:{{token}}

{
    "quantity": 10
}
### GET getRatingAndReviews
GET  /getRatingAndReviews?isSeller=false HTTP/1.1
Host:{{host}}
Content-Type: application/json

### ADD reviewAnd Rating for Item
POST  /saveRatingAndReviews HTTP/1.1
Host:{{host}}
Content-Type: application/json
userId:{{userid}}
token:{{token}}
itemId:{{itemId}}

{
    "review": "Not good",
    "rating":1
}
### ADD reviewAnd Rating for seller
POST  /saveRatingAndReviews?isSeller=true HTTP/1.1
Host:{{host}}
Content-Type: application/json
userId:{{userid}}
token:{{token}}
sellerId:{{sellerId}}

{
    "review": "Bad Seller",
    "rating":1
}

### UPDATE reviewAnd Rating for Item
POST  /saveRatingAndReviews HTTP/1.1
Host:{{host}}
Content-Type: application/json
userId:{{userid}}
token:{{token}}
itemId:{{itemId}}

{
    "rating":1
}
### UPDATE reviewAnd Rating for seller
POST  /saveRatingAndReviews?isSeller=true HTTP/1.1
Host:{{host}}
Content-Type: application/json
userId:{{userid}}
token:{{token}}
sellerId:{{sellerId}}

{
    "review": "update very Good Seller",
    "rating":3
}

### DELETE rating and Review
DELETE  /deleteRatingAndReviews?isSeller=false HTTP/1.1
Host:{{host}}
Content-Type: application/json
userId:{{userid}}
token:{{token}}
itemId:{{itemId}}


### DELETE rating and Review
DELETE  /deleteRatingAndReviews HTTP/1.1
Host:{{host}}
Content-Type: application/json
userId:{{userid}}
token:{{token}}
reviewId:{{reviewId}}


### 

GET  /getCartItems HTTP/1.1
Host:{{host}}
Content-Type: application/json
userId:{{userid}}
itemId:{{itemId}}
token:{{token}}
